### ISSUE TITLE
Support *url.URL type

### ISSUE THREAD

**Issue by jasonkeene** [cloudfoundry/go-envstruct#6]
Right now we have to parse a `string` into a `*url.URL`.

https://github.com/cloudfoundry-incubator/loggregator-tools/blob/7d4fb82e11b57322b0b303e40183c96cdad04c25/log-cache-forwarders/cmd/syslog/config.go#L52-L56

That isn't great.

**Comment by bradylove** [comment]
@jasonkeene that type is already supported https://github.com/cloudfoundry/go-envstruct/blob/master/envstruct_test.go#L241.

**Comment by bradylove** [comment]
I have updated the README to reflect that `*url.URL` is supported.
